default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

test:
 adapter: sqlite3
 database: db/test.sqlite3
 pool: 5
 timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: collabtagdb
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5
  timeout: 5000
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
